  - name: Install the packages MySQL (MariaDB)
    apk:
      name: mysql
      state: latest
      update_cache: yes
    tags: 
      - mysql

  - name: Create directory for .sock file
    file:
      path: /run/mysqld
      state: directory
      owner: "{{ mysql_user }}"
      group: "{{ mysql_user }}"
    tags: 
      - mysql

  - name: Initialization of default schema
    shell: mysql_install_db --user=mysql --ldata=/var/lib/mysql/
    tags: 
      - mysql

  - name: Copy SQL-template with permissions
    template:
      src: ./grant.sql.j2
      dest: /tmp/grant.sql
    tags: 
      - mysql

  - name: Granting permissions
    shell: mysqld --user=root --bootstrap < /tmp/grant.sql
    tags: 
      - mysql

  - name: Adjusting default configuration [1]
    replace:
      path: /etc/my.cnf.d/mariadb-server.cnf
      regexp: '^skip-networking'
      replace: '#skip-networking'
    tags: 
      - mysql
  
  - name: Adjusting default configuration [2]
    replace:
      path: /etc/my.cnf.d/mariadb-server.cnf
      regexp: '^#bind'
      replace: 'bind'
    tags: 
      - mysql